VHBA: 2-argument k[un]map_atomic is deprecated in >=3.4-rc1
The 1-argument form of k[un]map_atomic was introduced in 2.6.37-rc1, and
the old 2-argument form is deprecated in 3.4-rc1 and higher. As a
result, building vhba for a 3.4-rc* kernel that has
CONFIG_ENABLE_WARN_DEPRECATED fails:

/tmp/cdemu/vhba-module/vhba.c: In function ‘do_request’:
/tmp/cdemu/vhba-module/vhba.c:487:33: error: ‘kmap_atomic_deprecated’ is
deprecated (declared at include/linux/highmem.h:125)
[-Werror=deprecated-declarations]
/tmp/cdemu/vhba-module/vhba.c:492:1: error: ‘__kunmap_atomic_deprecated’
is deprecated (declared at include/linux/highmem.h:135)
[-Werror=deprecated-declarations]
/tmp/cdemu/vhba-module/vhba.c: In function ‘do_response’:
/tmp/cdemu/vhba-module/vhba.c:570:33: error: ‘kmap_atomic_deprecated’ is
deprecated (declared at include/linux/highmem.h:125)
[-Werror=deprecated-declarations]
/tmp/cdemu/vhba-module/vhba.c:575:1: error: ‘__kunmap_atomic_deprecated’
is deprecated (declared at include/linux/highmem.h:135)
[-Werror=deprecated-declarations]
cc1: all warnings being treated as errors

To work around this problem, add vhba_k[un]map_atomic wrappers that
default to the 1-argument form of k[un]map_atomic for 2.6.37 and newer,
and to the old 2-argument form for older kernels.

Signed-off-by: Rok Mandeljc <rok.mandeljc@gmail.com>