cdemu-client: use list() when iterating over parameter dictionary items
Because we may remove an item from a dictionary during validation,
we need to use list(). Otherwise, python3 will throw the following
error: "RuntimeError: dictionary changed size during iteration".